export const CELL_CLICKED = 'CELL_CLICKED';
export const SELECTED_PIECE = 'SELECTED_PIECE';
export const PIECE_MOVED = 'PIECE_MOVED';
export const CALCULATE_PATH = 'CALCULATE_PATH';
export const PIECE_TRY_EAT = 'PIECE_TRY_EAT';
export const SWITCH_TURN = 'SWITCH_TURN';
