export const columns = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'];

export const initState = {
    selected : '',
    pieces: {
        'A8':{imgSrc: './assets/BRook.svg', type:'Rook', color:'Black'},
        'B8':{imgSrc: './assets/BKnight.svg', type:'Knight', color:'Black'},
        'C8':{imgSrc: './assets/BBishop.svg', type:'Bishop', color:'Black'},
        'D8':{imgSrc: './assets/BKing.svg', type:'King', color:'Black'},
        'E8':{imgSrc: './assets/BQueen.svg', type:'Queen', color:'Black'},
        'F8':{imgSrc: './assets/BBishop.svg', type:'Bishop', color:'Black'},
        'G8':{imgSrc: './assets/BKnight.svg', type:'Knight', color:'Black'},
        'H8':{imgSrc: './assets/BRook.svg', type:'Rook', color:'Black'},
        'A7':{imgSrc: './assets/BPawn.svg', type:'Pawn', color:'Black'},
        'B7':{imgSrc: './assets/BPawn.svg', type:'Pawn', color:'Black'},
        'C7':{imgSrc: './assets/BPawn.svg', type:'Pawn', color:'Black'},
        'D7':{imgSrc: './assets/BPawn.svg', type:'Pawn', color:'Black'},
        'E7':{imgSrc: './assets/BPawn.svg', type:'Pawn', color:'Black'},
        'F7':{imgSrc: './assets/BPawn.svg', type:'Pawn', color:'Black'},
        'G7':{imgSrc: './assets/BPawn.svg', type:'Pawn', color:'Black'},
        'H7':{imgSrc: './assets/BPawn.svg', type:'Pawn', color:'Black'},
        'A6':{},
        'B6':{},
        'G6':{},
        'C6':{},
        'F6':{},
        'D6':{},
        'E6':{},
        'H6':{},
        'A5':{},
        'B5':{},
        'G5':{},
        'C5':{},
        'F5':{},
        'D5':{},
        'E5':{},
        'H5':{},
        'A4':{},
        'B4':{},
        'G4':{},
        'C4':{},
        'F4':{},
        'D4':{},
        'E4':{},
        'H4':{},
        'A3':{},
        'B3':{},
        'G3':{},
        'C3':{},
        'F3':{},
        'D3':{},
        'E3':{},
        'H3':{},
        'A2':{imgSrc: './assets/WPawn.svg', type:'Pawn', color:'White'},
        'B2':{imgSrc: './assets/WPawn.svg', type:'Pawn', color:'White'},
        'C2':{imgSrc: './assets/WPawn.svg', type:'Pawn', color:'White'},
        'D2':{imgSrc: './assets/WPawn.svg', type:'Pawn', color:'White'},
        'E2':{imgSrc: './assets/WPawn.svg', type:'Pawn', color:'White'},
        'F2':{imgSrc: './assets/WPawn.svg', type:'Pawn', color:'White'},
        'G2':{imgSrc: './assets/WPawn.svg', type:'Pawn', color:'White'},
        'H2':{imgSrc: './assets/WPawn.svg', type:'Pawn', color:'White'},
        'A1':{imgSrc: './assets/WRook.svg', type:'Rook', color:'White'},
        'B1':{imgSrc: './assets/WKnight.svg', type:'Knight', color:'White'},
        'C1':{imgSrc: './assets/WBishop.svg', type:'Bishop', color:'White'},
        'D1':{imgSrc: './assets/WKing.svg', type:'King', color:'White'},
        'E1':{imgSrc: './assets/WQueen.svg', type:'Queen', color:'White'},
        'F1':{imgSrc: './assets/WBishop.svg', type:'Bishop', color:'White'},
        'G1':{imgSrc: './assets/WKnight.svg', type:'Knight', color:'White'},
        'H1':{imgSrc: './assets/WRook.svg', type:'Rook', color:'White'},
            }

}
