export const columns = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'];

export const initState = {
    selected : '',
    pieces: {
        'A8':{type:'Rook', color:'B'},
        'B8':{type:'Knight', color:'B'},
        'C8':{type:'Bishop', color:'B'},
        'D8':{type:'King', color:'B'},
        'E8':{type:'Queen', color:'B'},
        'F8':{type:'Bishop', color:'B'},
        'G8':{type:'Knight', color:'B'},
        'H8':{type:'Rook', color:'B'},
        'A7':{type:'Pawn', color:'B'},
        'B7':{type:'Pawn', color:'B'},
        'C7':{type:'Pawn', color:'B'},
        'D7':{type:'Pawn', color:'B'},
        'E7':{type:'Pawn', color:'B'},
        'F7':{type:'Pawn', color:'B'},
        'G7':{type:'Pawn', color:'B'},
        'H7':{type:'Pawn', color:'B'},
        'A6':{},
        'B6':{},
        'G6':{},
        'C6':{},
        'F6':{},
        'D6':{},
        'E6':{},
        'H6':{},
        'A5':{},
        'B5':{},
        'G5':{},
        'C5':{},
        'F5':{},
        'D5':{},
        'E5':{},
        'H5':{},
        'A4':{},
        'B4':{},
        'G4':{},
        'C4':{},
        'F4':{},
        'D4':{},
        'E4':{},
        'H4':{},
        'A3':{},
        'B3':{},
        'G3':{},
        'C3':{},
        'F3':{},
        'D3':{},
        'E3':{},
        'H3':{},
        'A2':{type:'Pawn', color:'W'},
        'B2':{type:'Pawn', color:'W'},
        'C2':{type:'Pawn', color:'W'},
        'D2':{type:'Pawn', color:'W'},
        'E2':{type:'Pawn', color:'W'},
        'F2':{type:'Pawn', color:'W'},
        'G2':{type:'Pawn', color:'W'},
        'H2':{type:'Pawn', color:'W'},
        'A1':{type:'Rook', color:'W'},
        'B1':{type:'Knight', color:'W'},
        'C1':{type:'Bishop', color:'W'},
        'D1':{type:'King', color:'W'},
        'E1':{type:'Queen', color:'W'},
        'F1':{type:'Bishop', color:'W'},
        'G1':{type:'Knight', color:'W'},
        'H1':{type:'Rook', color:'W'},
            }

}
